+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Aug 11 02:29:47 2023 - INFO  - Start to prepare the database config.
+ mkdir ./test_squashfs
+ echo helloworld
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Aug 11 02:29:48 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 11 02:29:50 2023 - INFO  - Start to run test.
+ mksquashfs ./test_squashfs ./test_squashfs.squashfs
oe_test_FSIO_create_squashfs.sh: line 30: mksquashfs: command not found
+ CHECK_RESULT 127 0 0 'mksquashfs failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='mksquashfs failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'mksquashfs failed'
+ LOG_ERROR 'mksquashfs failed'
+ message='mksquashfs failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mksquashfs failed'
Fri Aug 11 02:29:51 2023 - ERROR - mksquashfs failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_squashfs.sh line 31'
+ message='oe_test_FSIO_create_squashfs.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_squashfs.sh line 31'
Fri Aug 11 02:29:52 2023 - ERROR - oe_test_FSIO_create_squashfs.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ mount ./test_squashfs.squashfs /mnt
mount: /mnt: special device ./test_squashfs.squashfs does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32 0 0 'mount squashfs failed'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='mount squashfs failed'
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'mount squashfs failed'
+ LOG_ERROR 'mount squashfs failed'
+ message='mount squashfs failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mount squashfs failed'
Fri Aug 11 02:29:54 2023 - ERROR - mount squashfs failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_squashfs.sh line 33'
+ message='oe_test_FSIO_create_squashfs.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_squashfs.sh line 33'
Fri Aug 11 02:29:55 2023 - ERROR - oe_test_FSIO_create_squashfs.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ grep helloworld /mnt/testfile
grep: /mnt/testfile: No such file or directory
+ CHECK_RESULT 2 0 0 'read file failed'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='read file failed'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'read file failed'
+ LOG_ERROR 'read file failed'
+ message='read file failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'read file failed'
Fri Aug 11 02:29:57 2023 - ERROR - read file failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_squashfs.sh line 35'
+ message='oe_test_FSIO_create_squashfs.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_squashfs.sh line 35'
Fri Aug 11 02:29:59 2023 - ERROR - oe_test_FSIO_create_squashfs.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ touch /mnt/testfile
+ CHECK_RESULT 0 0 1 'touched file on readonly fs'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='touched file on readonly fs'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'touched file on readonly fs'
+ LOG_ERROR 'touched file on readonly fs'
+ message='touched file on readonly fs'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'touched file on readonly fs'
Fri Aug 11 02:30:00 2023 - ERROR - touched file on readonly fs
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_squashfs.sh line 37'
+ message='oe_test_FSIO_create_squashfs.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_squashfs.sh line 37'
Fri Aug 11 02:30:01 2023 - ERROR - oe_test_FSIO_create_squashfs.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 11 02:30:03 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 11 02:30:05 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Aug 11 02:30:06 2023 - INFO  - start environment cleanup.
+ umount /mnt
umount: /mnt: not mounted.
+ rm -rf ./test_squashfs.squashfs ./test_squashfs
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Aug 11 02:30:08 2023 - INFO  - Finish environment cleanup!
