+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Sep 12 00:26:04 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'aide gcc'
+ pkgs='aide gcc'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'aide gcc' --node 1 --tempfile ''
Tue Sep 12 00:26:13 2023 - INFO  - pkgs:(aide gcc) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ sed -i '$a/home DATAONLY' /etc/aide.conf
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Sep 12 00:26:13 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Sep 12 00:26:14 2023 - INFO  - Start to run test.
+ aide --init
Start timestamp: 2023-09-12 00:26:14 +0800 (AIDE 0.18.5)
AIDE successfully initialized database.
New AIDE database written to /var/lib/aide/aide.db.new.gz

Number of entries:	152657

---------------------------------------------------
The attributes of the (uncompressed) database(s):
---------------------------------------------------

/var/lib/aide/aide.db.new.gz
 MD5       : WHHvv8MhlrIMZnEp2Rt6ww==
 SHA1      : flog5tfL5QNpZ8lt0QSk7HLZKxw=
 SHA256    : qhjpUxC15ancj0tlITcJr4XbjphkSK3i
             IIQbwZfKY1c=
 SHA512    : Lm2U7Dd+IWRyzTGM54Fh4kM5l2yYtkLO
             xIy12PdTyBlx2tZNe1ZazVu3KtOV6aEl
             AVcsCoLYGoHJbXF98uEnTA==
 RMD160    : 8ixo0vlGcVkStH3YBGtKbZ4hX/o=
 TIGER     : ZufEvCKgcoe2JRvDk/WUUdsR7o9SWpKR
 CRC32     : 4RrvgA==
 WHIRLPOOL : um+HTf3jRLPfyV1P8PIg+bj7oxkcQ452
             d1v3oE6aCeSUOs7bzZXCOBLeU8ReprzB
             EAjs08XSBD4cSctX/Pp27w==
 GOST      : BoBcZDdQqigxVW/AKmuswsWuSgeelTUJ
             VxG3f/MjTK4=
 STRIBOG256: UqWmJhnyxM9ElHqELIXk9aMpSVZXtsbM
             HkIeixI9uz0=
 STRIBOG512: If1+DyRXkEz9u3+/R87negLazqYi5MaK
             I+cBO/cID+KvurwruYG+imZtCPQzVRko
             K2IB4i2cegwuxeTgnnFxNg==
 SM3       : KIrauoW3xjs0JDsaSFREzVHnhne7Uvmk
             VHvEpovGhAI=


End timestamp: 2023-09-12 00:36:56 +0800 (run time: 10m 42s)
+ CHECK_RESULT 0 0 0 'initialization failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='initialization failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ useradd testuser
+ aide -c /etc/aide.conf --update
+ grep -A 10 'Changed entries:'
+ grep /etc/group
f > ... mci.H..  : /etc/group
f < ... mc..H..  : /etc/group-
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /var/lib/aide/aide.db.new.gz
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ aide --check
+ grep Changed entries:
grep: entries:: No such file or directory
Tue Sep 12 00:56:01 2023 - ERROR - Timeout : Command 'bash -x oe_test_aide_update_database.sh' timed out after 1799.9997143 seconds
