+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Fri Sep 22 08:42:43 2023 - INFO  - Start environment preparation.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=vdb
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ DNF_INSTALL xfsdump
+ pkgs=xfsdump
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs xfsdump --node 1 --tempfile ''
Fri Sep 22 08:43:19 2023 - INFO  - pkgs:(xfsdump) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ echo 'n

p


+40M
n

p


+40M
w'
+ fdisk /dev/vdb

Welcome to fdisk (util-linux 2.39.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): 
Using default response p.
Partition number (1-4, default 1): Value out of range.
Partition number (1-4, default 1): First sector (2048-1023999, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-1023999, default 1023999): 
Created a new partition 1 of type 'Linux' and of size 40 MiB.

Command (m for help): Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): 
Using default response p.
Partition number (2-4, default 2): Value out of range.
Partition number (2-4, default 2): First sector (83968-1023999, default 83968): Last sector, +/-sectors or +/-size{K,M,G,T,P} (83968-1023999, default 1023999): 
Created a new partition 2 of type 'Linux' and of size 40 MiB.
Partition #2 contains a ext4 signature.

Command (m for help): 
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Fri Sep 22 08:43:21 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Fri Sep 22 08:43:22 2023 - INFO  - Start executing testcase.
+ mkdir /home/pv
+ pvcreate /dev/ -y
  No device found for /dev/.
+ vgcreate test /dev/ -y
  No device found for /dev/.
+ lvcreate -L 20MiB -n lv1 test -y
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 46'
+ message='oe_test_storage_xfs_Increase_size.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 46'
Fri Sep 22 08:43:25 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ mkfs.xfs -f /dev/mapper/test-lv1
Error accessing specified device /dev/mapper/test-lv1: No such file or directory
Usage: mkfs.xfs
/* blocksize */		[-b size=num]
/* config file */	[-c options=xxx]
/* metadata */		[-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1,
			    inobtcount=0|1,bigtime=0|1]
/* data subvol */	[-d agcount=n,agsize=n,file,name=xxx,size=num,
			    (sunit=value,swidth=value|su=num,sw=num|noalign),
			    sectsize=num
/* force overwrite */	[-f]
/* inode size */	[-i perblock=n|size=num,maxpct=n,attr=0|1|2,
			    projid32bit=0|1,sparse=0|1,nrext64=0|1]
/* no discard */	[-K]
/* log subvol */	[-l agnum=n,internal,size=num,logdev=xxx,version=n
			    sunit=value|su=num,sectsize=num,lazy-count=0|1]
/* label */		[-L label (maximum 12 characters)]
/* naming */		[-n size=num,version=2|ci,ftype=0|1]
/* no-op info only */	[-N]
/* prototype file */	[-p fname]
/* quiet */		[-q]
/* realtime subvol */	[-r extsize=num,size=num,rtdev=xxx]
/* sectorsize */	[-s size=num]
/* version */		[-V]
			devicename
<devicename> is required unless -d name=xxx is given.
<num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
      xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
<value> is xxx (512 byte blocks).
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 48'
+ message='oe_test_storage_xfs_Increase_size.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 48'
Fri Sep 22 08:43:26 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ mount /dev/mapper/test-lv1 /home/pv
mount: /home/pv: special device /dev/mapper/test-lv1 does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 50'
+ message='oe_test_storage_xfs_Increase_size.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 50'
Fri Sep 22 08:43:27 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ pvcreate /dev/ -y
  No device found for /dev/.
+ vgextend test /dev/ -y
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 53'
+ message='oe_test_storage_xfs_Increase_size.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 53'
Fri Sep 22 08:43:29 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ lvextend -L +10MiB /dev/mapper/test-lv1 /dev/ -y
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 55'
+ message='oe_test_storage_xfs_Increase_size.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 55'
Fri Sep 22 08:43:31 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ xfs_info /home/pv
xfs_info: cannot open /home/pv: Is a directory
+ lvextend -L +10MiB /dev/mapper/test-lv1 /dev/ -y
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 58'
+ message='oe_test_storage_xfs_Increase_size.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 58'
Fri Sep 22 08:43:33 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ xfs_growfs /home/pv -D 5500
+ grep 'blocks changed from 5120 to 5500'
xfs_growfs: /home/pv is not a mounted XFS filesystem
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 60'
+ message='oe_test_storage_xfs_Increase_size.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 60'
Fri Sep 22 08:43:34 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ xfs_growfs /home/pv
+ grep 'data blocks changed from 5500 to'
xfs_growfs: /home/pv is not a mounted XFS filesystem
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_xfs_Increase_size.sh line 62'
+ message='oe_test_storage_xfs_Increase_size.sh line 62'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_xfs_Increase_size.sh line 62'
Fri Sep 22 08:43:36 2023 - ERROR - oe_test_storage_xfs_Increase_size.sh line 62
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution.'
+ message='End of testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution.'
Fri Sep 22 08:43:37 2023 - INFO  - End of testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep 22 08:43:38 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Sep 22 08:43:40 2023 - INFO  - start environment cleanup.
+ umount /home/pv
umount: /home/pv: not mounted.
+ lvremove /dev/test/lv1 -y
  Volume group "test" not found
  Cannot process volume group test
+ vgremove /dev/test -y
  Volume group "test" not found
  Cannot process volume group test
+ pvremove /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ rm -rf /home/pv
+ echo 'd

d

w'
+ fdisk /dev/vdb

Welcome to fdisk (util-linux 2.39.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition number (1,2, default 2): 
Partition 2 has been deleted.

Command (m for help): Selected partition 1
Partition 1 has been deleted.

Command (m for help): 

Command (m for help): 
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Sep 22 08:43:42 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Fri Sep 22 08:43:44 2023 - INFO  - Finish environment cleanup.
