+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Tue Oct 10 20:58:10 2023 - INFO  - Start environment preparation.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=vdb
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ pvcreate -y /dev/ /dev/vdb
  No device found for /dev/.
  Physical volume "/dev/vdb" successfully created.
+ vgcreate openeulertest /dev/
  No device found for /dev/.
+ lvcreate -L 50MB -n test openeulertest -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Tue Oct 10 20:58:16 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Tue Oct 10 20:58:17 2023 - INFO  - Start executing testcase!
+ pvscan
+ grep /dev/
  PV /dev/vdb                      lvm2 [500.00 MiB]
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgextend openeulertest /dev/vdb -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ pvdisplay
+ grep vdb
  "/dev/vdb" is a new physical volume of "500.00 MiB"
  PV Name               /dev/vdb
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvmove /dev/ /dev/vdb
  Cannot use /dev/: device not found
  Run `pvmove --help' for more information.
+ CHECK_RESULT 3
+ actual_result=3
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 3 ']'
+ '[' 0 -eq 0 ']'
+ test 3x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 37'
+ message='oe_test_storage_lvm_split_VG.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 37'
Tue Oct 10 20:58:18 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ pvscan
+ grep /dev/vdb
+ grep openeulertest
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 39'
+ message='oe_test_storage_lvm_split_VG.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 39'
Tue Oct 10 20:58:18 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ lvchange -a n /dev/openeulertest/test
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 41'
+ message='oe_test_storage_lvm_split_VG.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 41'
Tue Oct 10 20:58:19 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ vgsplit openeulertest openeulertest1 /dev/
  Volume group "openeulertest" not found
  Failed to read VG openeulertest1.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 43'
+ message='oe_test_storage_lvm_split_VG.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 43'
Tue Oct 10 20:58:19 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ vgdisplay
+ grep openeulertest1
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 45'
+ message='oe_test_storage_lvm_split_VG.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 45'
Tue Oct 10 20:58:20 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ lvcreate -y -L 1G -n openeuler1 openeulertest1
  Volume group "openeulertest1" not found
  Cannot process volume group openeulertest1
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 47'
+ message='oe_test_storage_lvm_split_VG.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 47'
Tue Oct 10 20:58:21 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ mkfs.ext4 /dev/openeulertest1/openeuler1
mke2fs 1.47.0 (5-Feb-2023)
The file /dev/openeulertest1/openeuler1 does not exist and no size was specified.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 49'
+ message='oe_test_storage_lvm_split_VG.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 49'
Tue Oct 10 20:58:21 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ mount /dev/openeulertest1/openeuler1 /mnt
mount: /mnt: special device /dev/openeulertest1/openeuler1 does not exist.
       dmesg(1) may have more information after failed mount system call.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_split_VG.sh line 51'
+ message='oe_test_storage_lvm_split_VG.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_split_VG.sh line 51'
Tue Oct 10 20:58:22 2023 - ERROR - oe_test_storage_lvm_split_VG.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Tue Oct 10 20:58:22 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Oct 10 20:58:22 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Oct 10 20:58:23 2023 - INFO  - start environment cleanup.
+ umount /dev/openeulertest1/openeuler1
umount: /dev/openeulertest1/openeuler1: no mount point specified.
+ lvremove -y openeulertest/test openeulertest1/openeuler1
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
  Volume group "openeulertest1" not found
  Cannot process volume group openeulertest1
+ vgremove -y openeulertest openeulertest1
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
  Volume group "openeulertest1" not found
  Cannot process volume group openeulertest1
+ pvremove /dev/ /dev/vdb
  No device found for /dev/.
  Labels on physical volume "/dev/vdb" successfully wiped.
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Tue Oct 10 20:58:24 2023 - INFO  - Finish environment cleanup.
