+ source ./common/disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Mon Jun  5 18:03:05 2023 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Mon Jun  5 18:03:15 2023 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=vdb
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Mon Jun  5 18:03:27 2023 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Mon Jun  5 18:03:28 2023 - INFO  - Start executing testcase!
+ pvcreate -y /dev/vdb /dev/
  No device found for /dev/.
  Physical volume "/dev/vdb" successfully created.
+ CHECK_RESULT 5 0 0 'failed to creat PV'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='failed to creat PV'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'failed to creat PV'
+ LOG_ERROR 'failed to creat PV'
+ message='failed to creat PV'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to creat PV'
Mon Jun  5 18:03:30 2023 - ERROR - failed to creat PV
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgextend_002.sh line 30'
+ message='oe_test_lvm2_vgextend_002.sh line 30'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgextend_002.sh line 30'
Mon Jun  5 18:03:31 2023 - ERROR - oe_test_lvm2_vgextend_002.sh line 30
+ '[' 0 -eq 1 ']'
+ return 0
+ pvs
+ grep /dev/vdb
  /dev/vdb      lvm2 ---  500.00m 500.00m
+ pvs
+ grep /dev/
  /dev/vdb      lvm2 ---  500.00m 500.00m
+ CHECK_RESULT 0 0 0 'failed to creat PV'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat PV'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgcreate test /dev/vdb
  Volume group "test" successfully created
+ CHECK_RESULT 0 0 0 'failed to creat VG'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat VG'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgdisplay
+ grep 'VG Name'
+ grep test
  VG Name               test
+ CHECK_RESULT 0 0 0 'failed to creat PV'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat PV'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgextend --dataalignment 3 test /dev/
+ grep 'successfully extended'
  No device found for /dev/.
+ CHECK_RESULT 1 0 0 'failed to vgextend --dataalignment'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to vgextend --dataalignment'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to vgextend --dataalignment'
+ LOG_ERROR 'failed to vgextend --dataalignment'
+ message='failed to vgextend --dataalignment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to vgextend --dataalignment'
Mon Jun  5 18:03:34 2023 - ERROR - failed to vgextend --dataalignment
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgextend_002.sh line 38'
+ message='oe_test_lvm2_vgextend_002.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgextend_002.sh line 38'
Mon Jun  5 18:03:35 2023 - ERROR - oe_test_lvm2_vgextend_002.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ pvs
+ grep /dev/
+ grep test
  /dev/vdb   test lvm2 a--  496.00m 496.00m
+ CHECK_RESULT 0 0 0 'failed to creat PV'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat PV'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgremove -f test
  Volume group "test" successfully removed
+ vgcreate test /dev/vdb
+ grep 'successfully created'
  Volume group "test" successfully created
+ CHECK_RESULT 0 0 0 'failed to creat VG'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat VG'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 'successfully extended'
+ vgextend --dataalignmentoffset 3 test /dev/
  No device found for /dev/.
+ CHECK_RESULT 1 0 0 'failed to vgextend --dataalignmentoffset'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to vgextend --dataalignmentoffset'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to vgextend --dataalignmentoffset'
+ LOG_ERROR 'failed to vgextend --dataalignmentoffset'
+ message='failed to vgextend --dataalignmentoffset'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to vgextend --dataalignmentoffset'
Mon Jun  5 18:03:38 2023 - ERROR - failed to vgextend --dataalignmentoffset
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgextend_002.sh line 45'
+ message='oe_test_lvm2_vgextend_002.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgextend_002.sh line 45'
Mon Jun  5 18:03:39 2023 - ERROR - oe_test_lvm2_vgextend_002.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ vgremove -f test
  Volume group "test" successfully removed
+ vgcreate test /dev/vdb
+ grep 'successfully created'
  Volume group "test" successfully created
+ CHECK_RESULT 0 0 0 'failed to creat VG'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat VG'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 'successfully extended'
+ vgextend --reportformat basic test /dev/
  No device found for /dev/.
+ CHECK_RESULT 1 0 0 'failed to vgextend --reportformat basic'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to vgextend --reportformat basic'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to vgextend --reportformat basic'
+ LOG_ERROR 'failed to vgextend --reportformat basic'
+ message='failed to vgextend --reportformat basic'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to vgextend --reportformat basic'
Mon Jun  5 18:03:42 2023 - ERROR - failed to vgextend --reportformat basic
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgextend_002.sh line 50'
+ message='oe_test_lvm2_vgextend_002.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgextend_002.sh line 50'
Mon Jun  5 18:03:43 2023 - ERROR - oe_test_lvm2_vgextend_002.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ vgextend --help
+ grep 'Add physical volumes to a volume group'
  vgextend - Add physical volumes to a volume group
+ CHECK_RESULT 0 0 0 'failed to vgextend --help'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to vgextend --help'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgextend --version
+ grep 'LVM version'
  LVM version:     2.03.18(2)-git (2022-11-10)
+ CHECK_RESULT 0 0 0 'failed to test extend version'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to test extend version'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgremove -f test
  Volume group "test" successfully removed
+ grep 'successfully created'
+ vgcreate test /dev/vdb
  Volume group "test" successfully created
+ CHECK_RESULT 0 0 0 'failed to creat VG'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat VG'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgextend -t test /dev/
+ grep 'successfully extended'
  TEST MODE: Metadata will NOT be updated and volumes will not be (de)activated.
  No device found for /dev/.
+ CHECK_RESULT 1 0 0 'failed to vgextend -t'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to vgextend -t'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to vgextend -t'
+ LOG_ERROR 'failed to vgextend -t'
+ message='failed to vgextend -t'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to vgextend -t'
Mon Jun  5 18:03:46 2023 - ERROR - failed to vgextend -t
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgextend_002.sh line 59'
+ message='oe_test_lvm2_vgextend_002.sh line 59'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgextend_002.sh line 59'
Mon Jun  5 18:03:47 2023 - ERROR - oe_test_lvm2_vgextend_002.sh line 59
+ '[' 0 -eq 1 ']'
+ return 0
+ vgremove -f test
  Volume group "test" successfully removed
+ vgcreate test /dev/vdb
+ grep 'successfully created'
  Volume group "test" successfully created
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgextend -t test /dev/
+ grep 'successfully extended'
+ CHECK_RESULT 1 0 0 'failed to extend VG -t'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to extend VG -t'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to extend VG -t'
+ LOG_ERROR 'failed to extend VG -t'
+ message='failed to extend VG -t'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to extend VG -t'
Mon Jun  5 18:03:50 2023 - ERROR - failed to extend VG -t
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgextend_002.sh line 64'
+ message='oe_test_lvm2_vgextend_002.sh line 64'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgextend_002.sh line 64'
Mon Jun  5 18:03:51 2023 - ERROR - oe_test_lvm2_vgextend_002.sh line 64
+ '[' 0 -eq 1 ']'
+ return 0
+ vgremove -f test
  Volume group "test" successfully removed
+ vgcreate test /dev/vdb
+ grep 'successfully created'
  Volume group "test" successfully created
+ CHECK_RESULT 0 0 0 'failed to creat VG'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='failed to creat VG'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ vgextend -q test /dev/
+ grep 'successfully extended'
  No device found for /dev/.
+ CHECK_RESULT 1 0 0 'failed to extend VG -q'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='failed to extend VG -q'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'failed to extend VG -q'
+ LOG_ERROR 'failed to extend VG -q'
+ message='failed to extend VG -q'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to extend VG -q'
Mon Jun  5 18:03:53 2023 - ERROR - failed to extend VG -q
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_vgextend_002.sh line 69'
+ message='oe_test_lvm2_vgextend_002.sh line 69'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_vgextend_002.sh line 69'
Mon Jun  5 18:03:54 2023 - ERROR - oe_test_lvm2_vgextend_002.sh line 69
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Mon Jun  5 18:03:56 2023 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Jun  5 18:03:57 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Mon Jun  5 18:03:58 2023 - INFO  - Start environment cleanup.
+ vgremove -f test
  Volume group "test" successfully removed
+ pvremove -f /dev/vdb /dev/
  No device found for /dev/.
  Labels on physical volume "/dev/vdb" successfully wiped.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Mon Jun  5 18:04:00 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Mon Jun  5 18:04:01 2023 - INFO  - Finish environment cleanup.
