+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ cat
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Tue Sep 12 10:02:04 2023 - INFO  - Start environment preparation.
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Sep 12 10:02:04 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Tue Sep 12 10:02:04 2023 - INFO  - Start testing...
+ rpm -qa
+ grep gdb
gdbm-1.23-2.oe2309.x86_64
+ CHECK_RESULT 0 0 0 'Return value error'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Return value error'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cd /tmp
+ gcc test.c -g -o test
oe_test_gdb-breakpoints.sh: line 58: gcc: command not found
+ test -f /tmp/test
+ CHECK_RESULT 1 0 0 'compile test.c fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='compile test.c fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'compile test.c fail'
+ LOG_ERROR 'compile test.c fail'
+ message='compile test.c fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'compile test.c fail'
Tue Sep 12 10:02:04 2023 - ERROR - compile test.c fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gdb-breakpoints.sh line 60'
+ message='oe_test_gdb-breakpoints.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gdb-breakpoints.sh line 60'
Tue Sep 12 10:02:04 2023 - ERROR - oe_test_gdb-breakpoints.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ gdb /tmp/test
+ grep breakpoint /tmp/test.log
oe_test_gdb-breakpoints.sh: line 61: gdb: command not found
+ CHECK_RESULT 0 0 0 'certifi_test file error'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='certifi_test file error'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Sep 12 10:02:04 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Sep 12 10:02:04 2023 - INFO  - start environment cleanup.
+ rm -rf /tmp/test.log /tmp/test /tmp/test.c
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Tue Sep 12 10:02:04 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Tue Sep 12 10:02:04 2023 - INFO  - Finish environment cleanup!
