+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Mon Sep 11 23:16:16 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL dnf-automatic
+ pkgs=dnf-automatic
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs dnf-automatic --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpn6kgjpgt
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpn6kgjpgt
+ service=dnf-automatic-install.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-09-11 23:16:58'
+ status='inactive (dead)'
+ systemctl start dnf-automatic-install.service
Job for dnf-automatic-install.service failed because the control process exited with error code.
See "systemctl status dnf-automatic-install.service" and "journalctl -xeu dnf-automatic-install.service" for details.
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Mon Sep 11 23:17:09 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Mon Sep 11 23:17:09 2023 - INFO  - Start testing...
+ systemctl status dnf-automatic-install.service
+ grep Active
+ grep -v 'inactive (dead)'
     Active: failed (Result: exit-code) since Mon 2023-09-11 23:17:08 CST; 1s ago
+ CHECK_RESULT 0 0 1 'There is an error for the status of dnf-automatic-install.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error for the status of dnf-automatic-install.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error for the status of dnf-automatic-install.service'
+ LOG_ERROR 'There is an error for the status of dnf-automatic-install.service'
+ message='There is an error for the status of dnf-automatic-install.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error for the status of dnf-automatic-install.service'
Mon Sep 11 23:17:10 2023 - ERROR - There is an error for the status of dnf-automatic-install.service
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_dnf-automatic-install.sh line 35'
+ message='oe_test_service_dnf-automatic-install.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_dnf-automatic-install.sh line 35'
Mon Sep 11 23:17:10 2023 - ERROR - oe_test_service_dnf-automatic-install.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled dnf-automatic-install.service
+ service=dnf-automatic-install.service
++ systemctl is-enabled dnf-automatic-install.service
+ state=static
+ '[' static == enabled ']'
+ '[' static == disabled ']'
+ '[' static == masked ']'
+ '[' static == static ']'
+ LOG_INFO 'The unit files have no installation config,This means they are not meant to be enabled using systemctl.'
+ message='The unit files have no installation config,This means they are not meant to be enabled using systemctl.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'The unit files have no installation config,This means they are not meant to be enabled using systemctl.'
Mon Sep 11 23:17:11 2023 - INFO  - The unit files have no installation config,This means they are not meant to be enabled using systemctl.
+ journalctl --since '2023-09-11 23:16:58' -u dnf-automatic-install.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ grep -v libgpg-error
+ grep -v '_sasl_plugin_load failed on sasl_canonuser_init'
Sep 11 23:17:08 openeuler-riscv64 dnf-automatic[2787]: Error:
Sep 11 23:17:08 openeuler-riscv64 systemd[1]: dnf-automatic-install.service: Main process exited, code=exited, status=1/FAILURE
Sep 11 23:17:08 openeuler-riscv64 systemd[1]: dnf-automatic-install.service: Failed with result 'exit-code'.
Sep 11 23:17:08 openeuler-riscv64 systemd[1]: Failed to start dnf automatic install updates.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of dnf-automatic-install.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of dnf-automatic-install.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of dnf-automatic-install.service'
+ LOG_ERROR 'There is an error message for the log of dnf-automatic-install.service'
+ message='There is an error message for the log of dnf-automatic-install.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of dnf-automatic-install.service'
Mon Sep 11 23:17:11 2023 - ERROR - There is an error message for the log of dnf-automatic-install.service
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_dnf-automatic-install.sh line 38'
+ message='oe_test_service_dnf-automatic-install.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_dnf-automatic-install.sh line 38'
Mon Sep 11 23:17:12 2023 - ERROR - oe_test_service_dnf-automatic-install.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Mon Sep 11 23:17:12 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Sep 11 23:17:13 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon Sep 11 23:17:13 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpn6kgjpgt ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpn6kgjpgt
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon Sep 11 23:17:29 2023 - INFO  - End to restore the test environment.
